"""documents and chunks tables (HLD 7.4 schema + ACL columns)

Revision ID: b8ac0ffa5f4e
Revises: 6c5ae358d6a4
Create Date: 2026-08-20 09:33:06.639462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'b8ac0ffa5f4e'
down_revision: Union[str, None] = '6c5ae358d6a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pgvector extension must exist before any VECTOR column can be created.
    # Idempotent so this migration is safe even if Phase 1.0 already ran
    # `CREATE EXTENSION IF NOT EXISTS vector` by hand.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=71), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('authors', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['superseded_by'], ['documents.document_id'], ),
    sa.PrimaryKeyConstraint('document_id'),
    sa.UniqueConstraint('source_system', 'source_uri', 'content_hash', name='uq_document_source_hash')
    )
    op.create_index('ix_documents_source_uri', 'documents', ['source_uri'], unique=False)
    op.create_table('chunks',
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=71), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('content_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content)", persisted=True), nullable=True),
    sa.Column('functions', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('classification_tier', sa.String(length=32), nullable=False),
    sa.Column('effective_tier', sa.String(length=32), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('authors', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('project_ids', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('entities', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('chunk_acl_tokens', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by'], ['chunks.chunk_id'], ),
    sa.PrimaryKeyConstraint('chunk_id'),
    sa.UniqueConstraint('document_id', 'content_hash', name='uq_chunk_document_hash')
    )
    op.create_index('ix_chunks_chunk_acl_tokens', 'chunks', ['chunk_acl_tokens'], unique=False, postgresql_using='gin')
    op.create_index('ix_chunks_content_tsv', 'chunks', ['content_tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_chunks_document_id', 'chunks', ['document_id'], unique=False)
    op.create_index('ix_chunks_embedding_hnsw', 'chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_chunks_functions', 'chunks', ['functions'], unique=False, postgresql_using='gin')
    op.create_index('ix_chunks_project_ids', 'chunks', ['project_ids'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunks_project_ids', table_name='chunks', postgresql_using='gin')
    op.drop_index('ix_chunks_functions', table_name='chunks', postgresql_using='gin')
    op.drop_index('ix_chunks_embedding_hnsw', table_name='chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_chunks_document_id', table_name='chunks')
    op.drop_index('ix_chunks_content_tsv', table_name='chunks', postgresql_using='gin')
    op.drop_index('ix_chunks_chunk_acl_tokens', table_name='chunks', postgresql_using='gin')
    op.drop_table('chunks')
    op.drop_index('ix_documents_source_uri', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
    # Note: intentionally NOT dropping the vector extension on downgrade —
    # other schemas/tables in this DB may depend on it.
